# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5513c72b6c91b1c6b4c08690bf2bdf518046adfd27773b7953e94d0d868020c46958226fe6d5f4a41d82d8b9206f9ee8770e04d0a7a41e6a0546da0afc336d5e

test:
  secret_key_base: eda18b80d8560702d7d8a7416af99f0504c1deaaeb5abc4123a9dad7ed04162e20a4c5d2d32b2dca922a1b6577321d18d2928c244ee12842289b4d6196829ab7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
